name       : haste-applet
version    : 0.2.3
release    : 1
source     :
    - https://github.com/cybre/haste-applet/archive/0.2.3.tar.gz : b6a14518a3f5fcc6f8a6d6506a96019ccbceeea94b38bb48845b569472bbd824
license    : GPL-2.0
component  : budgie.desktop
summary    : A Budgie applet for pasting text to any haste server.
description: |
    A Budgie applet for pasting text to any haste server.
builddeps  : 
    - pkgconfig(budgie-1.0)
    - pkgconfig(libsoup-2.4)
    - vala
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install