name       : budgie-haste-applet
version    : 0.2.9
release    : 11
source     :
    - https://github.com/cybre/budgie-haste-applet/archive/v0.2.9.tar.gz : 6d9121bda449dfd84e8969561c8a9877648bc5b0970df78c998d41d8e82cdfc2
license    : GPL-2.0
component  : desktop.budgie
summary    : Post any text, be it code or prose, to various services directly from your desktop
description: |
    Post any text, be it code or prose, to various services directly from your desktop
replaces   : haste-applet
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install