name       : budgie-haste-applet
version    : 0.2.5
release    : 4
source     :
    - https://github.com/cybre/budgie-haste-applet/archive/0.2.5.tar.gz : 1efcac25b1528bd3a16894a8277c6d995f2b462b4318ef75e185c4398e09c781
license    : GPL-2.0
component  : budgie.desktop
summary    : A Budgie applet for pasting text to any haste server.
description: |
    A Budgie applet for pasting text to any haste server.
replaces   : haste-applet
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(libsoup-2.4)
    - vala
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
