name       : budgie-haste-applet
version    : 0.2.6
release    : 5
source     :
    - https://github.com/cybre/budgie-haste-applet/archive/0.2.6.tar.gz : bc03f5ef309a36a2b513c4c78ade9fb46775692b722546755e03846f0c8a3700
license    : GPL-2.0
component  : budgie.desktop
summary    : A Budgie applet for pasting text to any haste server.
description: |
    A Budgie applet for pasting text to any haste server.
replaces   : haste-applet
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(libsoup-2.4)
    - vala
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
