name       : budgie-haste-applet
version    : 0.2.8
release    : 10
source     :
    - https://github.com/cybre/budgie-haste-applet/releases/download/0.2.8/budgie-haste-applet-0.2.8.tar.xz : a39bf2aeea0c092d217b94c9e1cf42951d518207417be6684f6a4fa5364905d0
license    : GPL-2.0
component  : desktop.budgie
summary    : A Budgie applet for pasting text to any haste server.
description: |
    A Budgie applet for pasting text to any haste server.
replaces   : haste-applet
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(libsoup-2.4)
    - vala
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
