name       : budgie-haste-applet
version    : 0.2.9
release    : 12
source     :
    - git|https://github.com/cybre/budgie-haste-applet.git : master
license    : GPL-2.0
component  : desktop.budgie
summary    : Post any text, be it code or prose, to various services directly from your desktop
description: |
    Post any text, be it code or prose, to various services directly from your desktop
replaces   : haste-applet
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install