name       : budgie-haste-applet
version    : 0.2.7
release    : 8
source     :
    - https://github.com/cybre/budgie-haste-applet/archive/v0.2.7.tar.gz : 8127d42f928fd5f086b55816fa7b2b6c635670e3679486e09a6fde001ba13567
license    : GPL-2.0
component  : desktop.budgie
summary    : A Budgie applet for pasting text to any haste server.
description: |
    A Budgie applet for pasting text to any haste server.
replaces   : haste-applet
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(libsoup-2.4)
    - vala
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
